### ISSUE TITLE
KeyError: '_SOURCE_REALTIME_TIMESTAMP'

### ISSUE THREAD

**Issue by ganto** [scottwakeling/seat-inspect#9]
I tried to use `seat-inspect` on my Gentoo box with systemd. Unfortunately, it failed with the following error:

```
merkur ~ # seat-inspect -v
[...]
         - munin-node.service (loaded failed failed)
                 - result: exit-code since: 2015-03-26 15:40:21
                         - 2015-03-10 19:47:48 merkur systemd[1]: Starting Munin Node Service...
                                 - Subject: Unit munin-node.service has begun start-up
                         - Defined-By: systemd
                         - Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
                         - Unit munin-node.service has begun starting up.
Traceback (most recent call last):
  File "/usr/bin/seat-inspect", line 953, in <module>
    main()
  File "/usr/bin/seat-inspect", line 948, in main
    enumerate_units()
  File "/usr/bin/seat-inspect", line 787, in enumerate_units
    log_summaries(unit_type, units[unit_type])
  File "/usr/bin/seat-inspect", line 799, in log_summaries
    unit.log_summary("\t - ")
  File "/usr/bin/seat-inspect", line 749, in log_summary
    entry['_SOURCE_REALTIME_TIMESTAMP'].strftime("%Y-%m-%d %H:%M:%S"),
KeyError: '_SOURCE_REALTIME_TIMESTAMP'
```

This is my environment:

```
merkur ~ # systemctl --version
systemd 219
+PAM +AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

merkur ~ # python --version
Python 3.4.1
```

The reason is that the failed unit didn't fill this field:

```
Thu 2015-03-26 15:40:21.160314 CET [s=a780400ce30b4ccab9f60dfd371a8f5e;i=7a876f;b=29bc1fab0461414c88a665af2d33291e;m=e69fb4;t=51231fecdf17a;x=357dc33ba8f03a43]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _SYSTEMD_SLICE=system.slice
    _MACHINE_ID=8531fdb0416086742a05968e0000000d
    _HOSTNAME=merkur
    _TRANSPORT=stdout
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=munin-node
    MESSAGE=Can't locate Munin/Common/Defaults.pm in @INC (you may need to install the Munin::Common::Defaults module) (@INC contains: /etc/perl /usr/local/lib64/perl5/5.20.1/x86_64-linux-thread-multi /usr/local/lib64/perl5/5.20.1 /usr/li
    _COMM=munin-node
    _EXE=/usr/bin/perl
    _CMDLINE=/usr/bin/perl -wT /usr/sbin/munin-node
    _SYSTEMD_CGROUP=/system.slice/munin-node.service
    _SYSTEMD_UNIT=munin-node.service
    _BOOT_ID=29bc1fab0461414c88a665af2d33291e
    _PID=1150
```

**Comment by ganto** [comment]
Hmn, I cannot really see what's the problem. If I check a regular journal entry, the field is available and filled:

    Thu 2015-03-26 23:00:02.302355 CET [s=a780400ce30b4ccab9f60dfd371a8f5e;i=7a9f94;b=29bc1fab0461414c88a665af2d33291e;m=62556eb81;t=51238233e3d47;x=c056626ea1ebe464]
        _TRANSPORT=syslog
        PRIORITY=6
        SYSLOG_FACILITY=10
        SYSLOG_IDENTIFIER=fcron
        _UID=0
        _GID=0
        _COMM=fcron
        _CAP_EFFECTIVE=3fffffffff
        _AUDIT_LOGINUID=0
        _SYSTEMD_CGROUP=/system.slice/fcron.service
        _SYSTEMD_UNIT=fcron.service
        _SYSTEMD_SLICE=system.slice
        _MACHINE_ID=8531fdb0416086742a05968e0000000d
        _HOSTNAME=merkur
        MESSAGE=pam_unix(fcron:session): session closed for user root
        _AUDIT_SESSION=60
        _BOOT_ID=29bc1fab0461414c88a665af2d33291e
        SYSLOG_PID=30841
        _PID=30841
        _SOURCE_REALTIME_TIMESTAMP=1427407202302355

**Comment by scottwakeling** [comment]
I've run into both trusted fields being unset, and showing up in journalctl -o verbose but not being retrieved by python-systemd..

It looks like it's just not set in your message.

From journald docs:

"Fields prefixed with an underscore are trusted fields, i.e. fields that are implicitly added by the journal and cannot be altered by client code."

and

"_SOURCE_REALTIME_TIMESTAMP=

```
The earliest trusted timestamp of the message, if any is known that is different from the reception time of the journal. This is the time in microseconds since the epoch UTC, formatted as a decimal string."
```

I suppose the "if any is known" prevents this being reported as a bug upstream.

Let me know how my 'fix' works for you.
